error:
	echo Please run one of the commands to build \(q1, q2, q3\).

q1:
	gcc -std=c99 lib.c lib.h list.c list.h common.h common.c q1.c

q2:
	gcc -std=c99 lib.c lib.h list.c list.h common.h common.c q2.c

q3:
	gcc -std=c99 lib.c lib.h list.c list.h common.h common.c q3.c
